version: '3'

services:

  poc-app:
    image: berk76/poc-app:latest
    container_name: poc-app
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=poc-db
      - DB_USERNAME=web
      - DB_PASSWORD=change-it
      - TZ=Europe/Prague
    networks:
      - default

  poc-db:
    image: jacobalberty/firebird:v3.0.10
    container_name: poc-db
    restart: unless-stopped
    ports:
      - 3050:3050
    environment:
      - ISC_PASSWORD=change-it
      - FIREBIRD_DATABASE=MYPOCDB
      - FIREBIRD_USER=web
      - FIREBIRD_PASSWORD=change-it
      - TZ=Europe/Prague
    volumes:
      - ./poc-data/firebird:/firebird
    networks:
      - default

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1450"
      com.docker.network.bridge.default_bridge: "true"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "docker0"
