name: build

on:
  push:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        # https://github.com/actions/setup-java#supported-distributions
        distribution: 'zulu'
        java-version: 8
    
    - name: Build war file
      run: |
        cd poc-app
        mvn --no-transfer-progress package --file pom.xml

    - name: Build docker image
      run: |
        cp poc-app/target/*.war docker/ROOT.war
        cd docker
        docker build -t berk76/poc-app:latest .

    - name: Start containers
      run: |
        cd docker-compose
        docker-compose -f poc.yml up -d

    - name: Create schema
      run: |
        pwd
        cd docker-compose
        docker cp ../db-schema/database.sql poc-db:/firebird/
        docker cp ./create-schema.sh poc-db:/firebird/
        docker exec poc-db bash "/firebird/create-schema.sh"

    - name: Install Google Chrome
      run: |
        npx @puppeteer/browsers install chrome@stable
        google-chrome --version

    - name: Run test
      run: |
        cd poc-selenium
        mvn --no-transfer-progress package --file pom.xml

    - name: Archive screen shots
      uses: actions/upload-artifact@v3
      with:
        name: Screenshots
        path: poc-selenium/target/*.png

    - name: Stop containers
      if: always()
      run: |
        cd docker-compose
        docker-compose -f poc.yml down
